### ISSUE TITLE
Charybdis Sample Project

### ISSUE THREAD

**Issue by DanielHe4rt** [nodecosmos/charybdis#1]
Hey, how's going?

There's any sample project using Charybdis that I can inspect? Like a todo-list or something related? 

I really loved the simplicity on the usage and want to know more about, but I'm still a Rust newbie... Maybe we can bring more improvements on the base doc together as well!

Cheers.

**Comment by GoranBrkuljan** [comment]
Hey Daniel,

That's a great point. I'll add few sample projects to lib itself by end of the week. ATM, documentation is not well structured both in code and .md files, so all contributions, especially in these areas, are welcomed.

Let me know if you have specific ideas for example projects or we can go with simple use cases for now.

Best!
