### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by 617a7aa** [nodecosmos/charybdis#18]
Hiya, does this support using TLS to connect to scylla? If not, can we add a feature to enable that functionality?

**Comment by GoranBrkuljan** [comment]
For the main crate session is passed from the app, so there we don't need to do anything. However, within `charybdis-migrate` we create session in crate itself, and currently it doesn't support TLS. If you are interested, PR would be welcomed.

**Comment by 617a7aa** [comment]
Will PR this in if we need it for what I'm working on.

**Comment by GoranBrkuljan** [comment]
completed with https://github.com/nodecosmos/charybdis/releases/tag/v0.7.2
