### ISSUE TITLE
Composed Partition Keys in Materialized Views

### ISSUE THREAD

**Issue by DanielHe4rt** [nodecosmos/charybdis#24]
Hey! I'm trying to create a MV with two keys in the partition key but seems to not work. Maybe it's a syntax error. It's suppose to work?

```rust
#[charybdis_view_model(
table_name=timeline_liked,
base_table=timeline,
partition_keys=[(username, liked)], // <- 
clustering_keys=[created_at, tweet_id],
table_options = "CLUSTERING ORDER BY (created_at DESC)"
)]
pub struct TimelineLiked {
    pub username: Text,
    pub tweet_id: Uuid,
    pub author: Text,
    pub text: Text,
    pub liked: Boolean,
    pub bookmarked: Boolean,
    pub retweeted: Boolean,
    pub created_at: Timeuuid
}
```

The output:

![image](https://github.com/nodecosmos/charybdis/assets/6912596/16b5bf23-673f-4ea4-8bc0-b23efde1be9d)

The expected query to be executed:

```cql
CREATE MATERIALIZED VIEW IF NOT EXISTS timeline_liked AS
    SELECT
        text,
        created_at,
        tweet_id,
        retweeted,
        bookmarked,
        author,
        liked,
        username
    FROM 
        timeline
    WHERE
        username IS NOT NULL AND
        liked IS NOT NULL AND
        created_at IS NOT NULL AND
        tweet_id IS NOT NULL
PRIMARY KEY ((username, liked), created_at, tweet_id) WITH CLUSTERING ORDER BY (created_at DESC);
```

**Comment by GoranBrkuljan** [comment]
@DanielHe4rt you have Parentheses in you macro partition_key part: `[(username, liked)]`. It should be `[username, liked]`.

**Comment by GoranBrkuljan** [comment]
Agh, I see now, it won't correctly set partition key part.

**Comment by GoranBrkuljan** [comment]
fixed in https://github.com/nodecosmos/charybdis/releases/tag/v0.4.18

**Comment by DanielHe4rt** [comment]
@GoranBrkuljan I tested the new version 0.4.18 and seems to not work yet. Maybe the syntax changed?

**Comment by GoranBrkuljan** [comment]
It works. As I said in prev comment,  make sure you don't have parentheses here: `[(username, liked)]`.  It should be `[username, liked]`.
