### ISSUE TITLE
Enable delete by  LSI

### ISSUE THREAD

**Issue by 617a7aa** [nodecosmos/charybdis#27]
I'm pretty sure scylla supports this. I want to delete a row by it's partition key and a field included in an LSI. The macros don't generate this.

**Comment by GoranBrkuljan** [comment]
Delete by partition is available `model.delete_by_partition_key()` 


Will implement delete by LSI funs when I get a chance.

**Comment by GoranBrkuljan** [comment]
Sorry, looks like we can not delete by LSI. While we can delete by partial primary key (with whole partition key), we can not delete by LSI.
