### ISSUE TITLE
Empty set fails to deserialise back into empty hashset

### ISSUE THREAD

**Issue by 617a7aa** [nodecosmos/charybdis#33]
When a column with a `Set` type is inserted and defaulted (to become an empty hash set), it is stored in Scylla as `null`. When reading this, the crate fails to convert the `null` into an empty hashset. 

Apologies for bad image

![image](https://github.com/nodecosmos/charybdis/assets/67651251/242ad51a-8f69-4df0-81d7-e9ccda917d3e)

```
failed to find meals: NextRowError("SELECT chef, id, name, description, ingredients, allergens, dietary_requirements, images, added_on FROM meals WHERE chef = ?", FromRowError(BadCqlVal { err: ValIsNull, column: 7 }))
```

**Comment by GoranBrkuljan** [comment]
https://opensource.docs.scylladb.com/stable/cql/types.html#sets

ScyllaDB does not distinguish an empty collections from a missing value so using `Option<Set<T>>` is recommended.

**Comment by 617a7aa** [comment]
That's so dumb, the main driver should use an empty collection for this case lol. Thank you, saved the day once again!

**Comment by GoranBrkuljan** [comment]
I agree, it's bit unexpected behavior. Maybe we could have some kind of compile time checks if collection is not `Option` and raise an error.

**Comment by 617a7aa** [comment]
Driver changes tracked upstream [here](https://github.com/scylladb/scylla-rust-driver/issues/1001#issue-2297522054).
