### ISSUE TITLE
Community resources

### ISSUE THREAD

**Issue by kakserpom** [nodecosmos/charybdis#36]
It would be neat to have a Discord server or, less preferably, a Slack community.

**Comment by DanielHe4rt** [comment]
I also agree with that. If @GoranBrkuljan agree with, I can moderate there too or even check with Scylla to allocate some resources 👀 

Just saying...

**Comment by GoranBrkuljan** [comment]
Ok, let's do it : https://discord.gg/ZBBhsx4H
