### ISSUE TITLE
Macros aren't exported

### ISSUE THREAD

**Issue by Zk2u** [nodecosmos/charybdis#44]
I've put several models (eg, `Meal` in a crate and marked them as pub. I can use the associated functions and access the types from another crate, however I presume the macro rules are not exported as I get an error from the other crate when using `find_meal!` and other similar bits on the macros

**Comment by GoranBrkuljan** [comment]
I would say that using macro-generated rules from one crate to another crate is already not maintenance-friendly. Now if I understand, you would like to use it in another crate that interacts with crate where models are created. In principle, we could allow it, but I think that is really really hard to track.
