### ISSUE TITLE
Feature: unconditional find

### ISSUE THREAD

**Issue by kakserpom** [nodecosmos/charybdis#46]
There seem to be no way to query all rows from a table.

**Comment by DanielHe4rt** [comment]
This is something that I was looking for as well... For demos, this is extremely important for me at Scylla, and I'm currently using session.get_sesion() for that.

+1

**Comment by GoranBrkuljan** [comment]
Resolved in [v0.7.8](https://github.com/nodecosmos/charybdis/releases/tag/v0.7.8)
