### ISSUE TITLE
Partial model question

### ISSUE THREAD

**Issue by buixuankhai1204** [nodecosmos/charybdis#52]
In some cases, we need to  create a partial model then find by primary key and return data with the partial model type?

**Comment by buixuankhai1204** [comment]
Thank you for your project <3

**Comment by GoranBrkuljan** [comment]
> In some cases, we need to  create a partial model then find by primary key and return data with the partial model type?

You can use partial model just like every other model:  

E.g. 

```rust
partial_model!(OwnerPost, id, owner_id)

OwnerPost {
  id: foo,
  owner_id: bar
}.find_by_primary_key().execute(..).await?
  
```

**Comment by GoranBrkuljan** [comment]
Sorry, I missed this. You can use parital_model just like you use native one, just don't forget fields that make up primary key. So you can do `FooPartialModel::find_by_primary_key` or `FooPartialModel {..}.update()` , etc.

**Comment by buixuankhai1204** [comment]
And can I export the FooPartialModel struct and call in another function? because I want to get this struct like a response function type.

**Comment by GoranBrkuljan** [comment]
It is gonna be defined as `pub struct FooPartialModel {..}` so you can use it wherever you need it.
