### ISSUE TITLE
Escape column names within queries to allow keywords as column names

### ISSUE THREAD

**Issue by GoranBrkuljan** [nodecosmos/charybdis#57]
In this [PR](https://github.com/nodecosmos/charybdis/pull/55) we updated column names and insert bind markers in case reserved keywords are used for column names, but we also need to update other clauses and use cases.

- [ ] insert, set, where clauses for fields and bind markers
- [ ] add, drop and create index queries for charybdis migrations

I think most of the changes goes to charybdis-macros/src/traits/fields/query.rs and charybdis-migrate/src/model/runner.rs, but we need to check all queries.

**Comment by GoranBrkuljan** [comment]
@dracarys18  do you have time to take over this?

**Comment by dracarys18** [comment]
Sure

**Comment by GoranBrkuljan** [comment]
Will not implement for now https://github.com/nodecosmos/charybdis/pull/58.
