### ISSUE TITLE
Proposal: Replace explicit re-exports from `scylla` with entire lib

### ISSUE THREAD

**Issue by theelderbeever** [nodecosmos/charybdis#63]
The `charybdis/src/lib.rs` perform explicit re-exports of types from the underlying `scylla` driver library. This however, runs into some issues such as not being able to import needed classes. One example is that multiple times throughout the docs passing `CachingSession` is mentioned. However, from what I can tell there is no way to access this type without add `scylla` as a separate dependency, aligning the version, and importing from the there.

Consider replacing `src/lib.rs`
```rust
pub mod scylla {
    pub use scylla::frame::response::cql_to_rust::FromRowError;
    pub use scylla::frame::response::result::{CqlValue, Row};
    pub use scylla::serialize::value::SerializeValue;
    pub use scylla::statement::PagingState;
    pub use scylla::transport::iterator::TypedRowStream;
}
```

with
```rust
pub use scylla;
```
or 
```rust
pub mod scylla {
    pub use scylla::*;
    pub use scylla::frame::response::cql_to_rust::FromRowError;
    pub use scylla::frame::response::result::{CqlValue, Row};
    pub use scylla::serialize::value::SerializeValue;
    pub use scylla::statement::PagingState;
    pub use scylla::transport::iterator::TypedRowStream;
}
```

**Comment by GoranBrkuljan** [comment]
I agree. I will do it, as I need to update macros.

**Comment by GoranBrkuljan** [comment]
Let's go with second soultion:


```rust
pub mod scylla {
    pub use scylla::*;
    pub use scylla::frame::response::cql_to_rust::FromRowError;
    pub use scylla::frame::response::result::{CqlValue, Row};
    pub use scylla::serialize::value::SerializeValue;
    pub use scylla::statement::PagingState;
    pub use scylla::transport::iterator::TypedRowStream;
}
```

so we can have everything that we need for our macros easily accessible.

**Comment by GoranBrkuljan** [comment]
Updated in [v0.7.10](https://github.com/nodecosmos/charybdis/releases/tag/v0.7.10).

**Comment by theelderbeever** [comment]
Thanks @GoranBrkuljan!
