### ISSUE TITLE
[Idea] Charybdis Migrate: Keyspaces

### ISSUE THREAD

**Issue by DanielHe4rt** [nodecosmos/charybdis#8]
I was wondering if there's any possibility to create **Keyspaces** directly from a file inside **models/** folder. Something like: `src/models/keyspaces.rs`

Also set it as default for each model in the like:

```rust
#[charybdis_model(
keyspace_name = "leaderboard"
table_name = song_leaderboard,
partition_keys = [song_id, modifiers, difficulty, instrument],
clustering_keys = [player_id, score],
global_secondary_indexes = [],
local_secondary_indexes = [],
table_options = "
  CLUSTERING ORDER BY (player_id ASC, score DESC)
",
)]
```

Even if it's just ONE keyspace, it would be better to keep re-running these migrations from scratch...

Thanks in advance!

**Comment by GoranBrkuljan** [comment]
I am not sure about this. Correct me if I am wrong, but  we would usually use single keyspace per app (or service) and we usually define keyspace on session level with `use_keyspace`. If we allow multiple keyspaces we would have to integrate keyspace into query and we would have to require definition of it for each model which might introduce overhead. Let me know about common use cases for this, but for now I don't think we should implement this.
